export interface QualityPublicApiContract {
  readonly name: string;
  readonly package: "@doctui/core" | "@doctui/dates" | "@doctui/notifications";
  readonly source: string;
  readonly props: readonly string[];
  readonly events: readonly string[];
  readonly slots: readonly string[];
}

export const QUALITY_PUBLIC_API = [
  {
    name: "TextInput",
    package: "@doctui/core",
    source: "packages/core/src/components/TextInput.ts",
    props: [
      "modelValue",
      "id",
      "label",
      "description",
      "error",
      "required",
      "size",
      "radius",
      "disabled",
      "readonly",
      "type",
      "placeholder",
      "leftSection",
      "rightSection",
      "clearable",
      "classNames",
      "styles",
    ],
    events: ["update:modelValue", "clear"],
    slots: ["leftSection", "rightSection"],
  },
  {
    name: "SegmentedControl",
    package: "@doctui/core",
    source: "packages/core/src/components/SegmentedControl.ts",
    props: ["modelValue", "data", "ariaLabel", "size", "radius", "disabled"],
    events: ["update:modelValue"],
    slots: [],
  },
  {
    name: "Combobox",
    package: "@doctui/core",
    source: "packages/core/src/components/Combobox.ts",
    props: [
      "modelValue",
      "data",
      "id",
      "multiple",
      "searchable",
      "clearable",
      "label",
      "description",
      "error",
      "required",
      "disabled",
      "placeholder",
      "ariaLabel",
      "nothingFound",
      "size",
      "radius",
    ],
    events: ["update:modelValue", "clear"],
    slots: ["option", "empty"],
  },
  {
    name: "TagsInput",
    package: "@doctui/core",
    source: "packages/core/src/components/TagsInput.ts",
    props: [
      "modelValue",
      "id",
      "name",
      "label",
      "description",
      "error",
      "required",
      "disabled",
      "readonly",
      "placeholder",
      "ariaLabel",
      "clearable",
      "maxTags",
      "separator",
      "size",
      "radius",
    ],
    events: ["update:modelValue", "add", "remove", "clear"],
    slots: ["tag"],
  },
  {
    name: "Menu",
    package: "@doctui/core",
    source: "packages/core/src/components/OverlayExtras.ts",
    props: ["modelValue", "data", "closeOnClickOutside"],
    events: ["update:modelValue", "select"],
    slots: ["target"],
  },
  {
    name: "Modal",
    package: "@doctui/core",
    source: "packages/core/src/components/Modal.ts",
    props: [
      "modelValue",
      "title",
      "ariaLabel",
      "size",
      "radius",
      "centered",
      "closeOnEscape",
      "closeOnClickOutside",
      "withCloseButton",
      "withOverlay",
      "overlayProps",
      "lockScroll",
      "trapFocus",
      "returnFocus",
      "portalTarget",
    ],
    events: ["update:modelValue"],
    slots: ["default", "footer"],
  },
  {
    name: "Drawer",
    package: "@doctui/core",
    source: "packages/core/src/components/Drawer.ts",
    props: [
      "modelValue",
      "title",
      "ariaLabel",
      "position",
      "size",
      "radius",
      "closeOnEscape",
      "closeOnClickOutside",
      "withCloseButton",
      "withOverlay",
      "overlayProps",
      "lockScroll",
      "trapFocus",
      "returnFocus",
      "portalTarget",
    ],
    events: ["update:modelValue"],
    slots: ["default", "footer"],
  },
  {
    name: "DatePicker",
    package: "@doctui/dates",
    source: "packages/dates/src/DatePicker.ts",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "placeholder",
      "minDate",
      "maxDate",
      "disabled",
      "clearable",
      "locale",
      "firstDayOfWeek",
      "size",
      "radius",
    ],
    events: ["update:modelValue", "select", "blur", "clear"],
    slots: [],
  },
  {
    name: "Notifications",
    package: "@doctui/notifications",
    source: "packages/notifications/src/index.ts",
    props: ["store", "position", "cleanOnUnmount"],
    events: [],
    slots: [],
  },
] as const satisfies readonly QualityPublicApiContract[];

export function getQualityPublicApi(name: string) {
  return QUALITY_PUBLIC_API.find((contract) => contract.name === name);
}
