export const DOCTUI_DATES_METADATA = [
  {
    name: "Calendar",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Accessible token-driven month grid with adjacent-month days, range constraints and keyboard navigation.",
    props: [
      "id",
      "modelValue",
      "month",
      "minDate",
      "maxDate",
      "locale",
      "firstDayOfWeek",
      "disabled",
      "ariaLabel",
    ],
    accessibility: [
      "Uses grid/row/gridcell semantics with one roving tab stop.",
      "Arrow keys move by day/week, Home and End move within the week, and PageUp/PageDown move across months.",
      "The current date uses aria-current=date and the selected date uses aria-selected.",
    ],
  },
  {
    name: "DateInput",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Native date field that reuses doctui core field geometry, sizing and validation states.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "minDate",
      "maxDate",
      "disabled",
      "clearable",
      "size",
      "radius",
    ],
    accessibility: [
      "Reuses the core TextInput label, description, error and SSR-safe ID relationships.",
      "Keeps native date input semantics while sharing doctui visual field states.",
      "When no visible label is supplied, ariaLabel or the default Date accessible name is used.",
    ],
  },
  {
    name: "DatePicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Doctui-styled readonly date field with formatted display value and an accessible calendar popup.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "placeholder",
      "minDate",
      "maxDate",
      "disabled",
      "clearable",
      "locale",
      "firstDayOfWeek",
      "size",
      "radius",
    ],
    accessibility: [
      "Uses a readonly text field rather than browser-native date chrome for the custom picker surface.",
      "The popup trigger exposes aria-expanded, aria-controls and aria-haspopup=grid.",
      "Escape closes the popup and restores trigger focus; pointer input outside closes it without stealing focus.",
      "Disabled state is forwarded to the field, actions and calendar.",
    ],
  },
  {
    name: "DateTimePicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Native date-time field that reuses doctui core field geometry, sizing and validation states.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "disabled",
      "clearable",
      "size",
      "radius",
    ],
    accessibility: [
      "Uses the same core field relationships and native control semantics as DateInput.",
    ],
  },
  {
    name: "MonthPicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Keyboard-navigable month listbox rendered in the shared doctui date surface.",
    props: ["modelValue", "year", "locale", "disabled", "ariaLabel"],
    accessibility: [
      "Uses listbox/option semantics with aria-selected and roving keyboard focus.",
    ],
  },
  {
    name: "YearPicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Keyboard-navigable year listbox rendered in the shared doctui date surface.",
    props: ["modelValue", "minYear", "maxYear", "disabled", "ariaLabel"],
    accessibility: [
      "Uses listbox/option semantics with aria-selected and roving keyboard focus.",
    ],
  },
] as const;
