export const DOCTUI_DATES_METADATA = [
  {
    name: "Calendar",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Accessible token-driven month grid with adjacent-month days, range constraints and keyboard navigation.",
    props: [
      "id",
      "modelValue",
      "month",
      "minDate",
      "maxDate",
      "locale",
      "firstDayOfWeek",
      "disabled",
      "ariaLabel",
      "headerInteractive",
    ],
    accessibility: [
      "Uses grid/row/gridcell semantics with one roving tab stop.",
      "Arrow keys move by day/week, Home and End move within the week, and PageUp/PageDown move across months.",
      "The current date uses aria-current=date and the selected date uses aria-selected.",
      "When headerInteractive is enabled, the month/year title becomes a keyboard-accessible view switch trigger.",
    ],
  },
  {
    name: "DateInput",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Editable localized date field with strict ISO model values and the shared doctui day/month/year picker dialog.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "placeholder",
      "minDate",
      "maxDate",
      "locale",
      "firstDayOfWeek",
      "disabled",
      "clearable",
      "size",
      "radius",
    ],
    accessibility: [
      "Reuses the core TextInput label, description, error and SSR-safe ID relationships.",
      "The text field stays editable while the calendar action opens the same custom dialog used by DatePicker.",
      "Typed localized dates are normalized back to strict YYYY-MM-DD model values only when valid and in range.",
      "The calendar action exposes aria-expanded, aria-controls and aria-haspopup=dialog.",
    ],
  },
  {
    name: "DatePicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Doctui-styled readonly date field with day, month and year picker views in one accessible dialog surface.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "placeholder",
      "minDate",
      "maxDate",
      "disabled",
      "clearable",
      "locale",
      "firstDayOfWeek",
      "size",
      "radius",
    ],
    accessibility: [
      "Uses a readonly text field rather than browser-native date chrome for the custom picker surface.",
      "The trigger exposes aria-expanded, aria-controls and aria-haspopup=dialog.",
      "The dialog switches between grid-based day selection and listbox-based month/year selection without leaving the picker.",
      "Escape closes the popup and restores trigger focus; pointer input outside closes it without stealing focus.",
      "Disabled state is forwarded to the field, actions and picker views.",
    ],
  },
  {
    name: "DateTimePicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Custom doctui date-time field combining the shared day/month/year picker with explicit hour and minute controls.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "placeholder",
      "minDate",
      "maxDate",
      "locale",
      "firstDayOfWeek",
      "disabled",
      "clearable",
      "size",
      "radius",
    ],
    accessibility: [
      "Uses the core field label, description and error relationships with a readonly text trigger.",
      "The custom picker opens as a dialog instead of invoking browser-native datetime chrome.",
      "Hour and minute controls have explicit accessible names, and Apply commits the draft date and time.",
      "Escape closes the dialog and restores trigger focus.",
    ],
  },
  {
    name: "MonthPicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Keyboard-navigable month listbox rendered in the shared doctui date surface.",
    props: [
      "modelValue",
      "year",
      "locale",
      "disabled",
      "ariaLabel",
      "headerInteractive",
    ],
    accessibility: [
      "Uses listbox/option semantics with aria-selected and roving keyboard focus.",
      "When headerInteractive is enabled, the year title becomes a keyboard-accessible switch to year selection.",
    ],
  },
  {
    name: "NativeDateInput",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Explicit browser-native date input wrapper that keeps OS date picker semantics while sharing doctui core field geometry.",
    props: [
      "id",
      "modelValue",
      "label",
      "description",
      "error",
      "ariaLabel",
      "minDate",
      "maxDate",
      "disabled",
      "clearable",
      "size",
      "radius",
    ],
    accessibility: [
      "Keeps native input[type=date] semantics and browser/OS picker behavior.",
      "Reuses core field label, description, error, clear, disabled and SSR-safe ID relationships.",
      "Use DateInput when editable text and a visually consistent doctui picker are preferred.",
    ],
  },
  {
    name: "YearPicker",
    package: "@doctui/dates",
    category: "inputs",
    description:
      "Keyboard-navigable paged year listbox with previous/next range navigation in the shared doctui date surface.",
    props: [
      "modelValue",
      "minYear",
      "maxYear",
      "pageSize",
      "disabled",
      "ariaLabel",
    ],
    accessibility: [
      "Uses listbox/option semantics with aria-selected and roving keyboard focus.",
      "Previous years and Next years buttons expose bounded range navigation without requiring a long scroll.",
      "The current year uses aria-current=date when visible.",
    ],
  },
] as const;
